name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: taskmanageracr20260914
  IMAGE_NAME: azure-task-manager
  APP_NAME: fejaan-task-manager-2026
  RESOURCE_GROUP: rg-azure-task-manager

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --container-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Restart App Service
        run: |
          az webapp restart \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME
